# Generated by Django 5.2.2 on 2025-06-13 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PracticeVarity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image", models.ImageField(upload_to="practice/")),
                ("date_added", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("RD", "READING"),
                            ("WR", "WRITING"),
                            ("LR", "LEARNING"),
                            ("SL", "SOLVING"),
                            ("RB", "REMEMBERING"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
