# Generated by Django 5.2.2 on 2025-06-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="practicevarity",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="practicevarity",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
