# Generated by Django 5.2.2 on 2025-06-17 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0002_practicevarity_description_practicevarity_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="practicevarity",
            name="price",
        ),
        migrations.AddField(
            model_name="practicevarity",
            name="time_req",
            field=models.IntegerField(default=0),
        ),
    ]
